Repository AnalogIO/coffeecard_app, pull requests merged in 2022-05, with the labels that each got.

#253 Update tickets icon
  lib/widgets/components/tickets/shop_section.dart
  lib/widgets/pages/home_page.dart
Labels: quick-pick

#264 Fix typo
  lib/base/strings.dart
Labels: quick-pick, P0

#259 Sort owned tickets by their product id
  lib/data/repositories/v1/ticket_repository.dart
Labels: quick-pick

#272 Adjust shimmer bg color to avoid black borders
  lib/widgets/components/helpers/shimmer_builder.dart
Labels: enhancement, quick-pick

#252 Fix #251 (User can change name to be empty)
  lib/widgets/components/entry/register/name_body.dart
Labels: quick-pick

#296 Bump Pipelines to Flutter v3.0.0
  .github/workflows/firebase.yml
  .github/workflows/flutter.yml
Labels: P0

#304 Release Flutter App to Play Store and App Store Connect
  .github/scripts/setup-certs.command
  .github/workflows/build.yml
  .github/workflows/firebase.yml
  .github/workflows/flutter.yml
  .github/workflows/release.yml
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/dk/analog/digitalclipcard/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/ExportOptions.plist
  ios/Runner/Info.plist
  ios/exportOptions.dev.plist
  ios/exportOptions.prod.plist
  lib/data/api/coffee_card_api_constants.dart
  lib/service_locator.dart
Labels: android, ios, P0

#307 feat: save encoded passcode in secure storage
  lib/cubits/authentication/authentication_cubit.dart
  lib/cubits/login/login_cubit.dart
  lib/cubits/register/register_cubit.dart
  lib/cubits/user/user_cubit.dart
  lib/data/repositories/shared/account_repository.dart
  lib/data/storage/secure_storage.dart
  lib/models/account/update_user.dart
  lib/utils/encode_passcode.dart
  lib/utils/reactivation_authenticator.dart
Labels: P0

#317 Update OpenApi specifications
  lib/models/purchase/payment.dart
  lib/payment/mobilepay_service.dart
  lib/widgets/components/purchase/purchase_overlay.dart
  lib/widgets/pages/tickets/buy_tickets_page.dart
  openapi/coffeecard_api.swagger.json
  openapi/coffeecard_api_v2.swagger.json
Labels: enhancement

#315 Firebase Crashlytics, Analytics and Performance setup
  android/app/build.gradle
  android/build.gradle
  ios/firebase_app_id_file.json
  lib/cubits/login/login_cubit.dart
  lib/cubits/purchase/purchase_cubit.dart
  lib/cubits/register/register_cubit.dart
  lib/firebase_options.dart
  lib/main.dart
  lib/models/purchase/payment.dart
  lib/payment/mobilepay_service.dart
  lib/service_locator.dart
  lib/utils/firebase_analytics_event_logging.dart
  lib/widgets/pages/tickets/buy_single_drink_page.dart
  lib/widgets/pages/tickets/buy_tickets_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#314 Only trigger release for app relevant files and folders
  .github/workflows/release.yml
Labels: enhancement

#318 Open Privacy Policy in external browser
  lib/base/strings.dart
  lib/data/api/coffee_card_api_constants.dart
  lib/payment/mobilepay_service.dart
  lib/payment/payment_handler.dart
  lib/utils/launch.dart
  lib/widgets/components/contributor_card.dart
  lib/widgets/components/purchase/purchase_overlay.dart
  lib/widgets/pages/settings/credits_page.dart
  lib/widgets/pages/settings/settings_page.dart
Labels: enhancement
