Repository AnalogIO/coffeecard_app, pull requests merged in 2023-05, with the labels that each got.

#453 Update Coffee Card API Server Urls
  .env.develop
  .env.production
Labels: quick-pick

#454 Trigger release when .env files are changes
  .github/workflows/release.yml
Labels: quick-pick

#458 Disable showing opening hours
  lib/features/ticket/presentation/pages/tickets_page.dart
  lib/widgets/pages/settings/settings_page.dart
Labels: quick-pick

#475 chore: update Bloc packages
  pubspec.lock
  pubspec.yaml
Labels: quick-pick

#472 test(utils): Improve String.capitalize() and add tests
  lib/core/extensions/string_extensions.dart
  test/core/extensions/string_extensions_test.dart
Labels: quick-pick, code/dev

#476 chore: bump flutter required version to 3.10.2
  .github/workflows/build.yml
  README.md
  pubspec.lock
  pubspec.yaml
Labels: quick-pick

#473 refactor(settings): tidy up `settings_page.dart`
  lib/widgets/pages/settings/settings_page.dart
Labels: code/dev
